# See the file config/install/advertiser.advertiser.yml

advertiser.advertiser:
  type: config_object
  label: 'Advertiser'
mapping:
  name:
    type: string
    label: 'Name'
  description:
    type: srting
    label: 'Description'
  lurl:
    type: srting
    label: 'Url'